layout_spectrum: 0.929190256204825
typography_spectrum: 0.831145926117436
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.9860380665668388
  lightness: 0.5538511780676165
  saturation: 0.12519549595376495
  rhythmicContrast: 0.9983461250409041
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: dandydanny
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/623c0b98-99b6-44fc-b744-ce6ff8d52929.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/623c0b98-99b6-44fc-b744-ce6ff8d52929.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: DandyDannyLikesThese
description: Things I like
github: true
author:
  name: Daniel
  url: 'https://twitter.com/dandydanny'
